# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('real_name', models.CharField(blank=True, max_length=60)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('affliation', models.CharField(blank=True, max_length=100)),
                ('base_of_operations', models.CharField(blank=True, max_length=100)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('armour', models.IntegerField(blank=True, null=True)),
                ('shield', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('role', models.CharField(choices=[('OF', 'Offense'), ('DE', 'Defense'), ('TA', 'Tank'), ('SU', 'Support')], max_length=2)),
            ],
        ),
    ]
