# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'', blank=True),
            preserve_default=False,
        ),
    ]
