# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 17:19
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sub_role',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SN', 'Sniper'), ('BU', 'Builder'), ('HE', 'Healer')], max_length=8),
        ),
    ]
