# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_character_sub_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
