# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='game_mode',
            field=models.CharField(blank=True, choices=[('AS', 'Assault'), ('ES', 'Escort'), ('HY', 'Hybrid'), ('CO', 'Control'), ('AR', 'Arcade'), ('EV', 'Event'), ('AR', 'Arena'), ('DM', 'Death Match')], max_length=2),
        ),
        migrations.AlterField(
            model_name='map',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
