# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180425_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='affliation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
