# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180426_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='game_mode',
            field=models.CharField(blank=True, choices=[('AS', 'Assault'), ('ES', 'Escort'), ('HY', 'Hybrid'), ('CO', 'Control'), ('AR', 'Arcade'), ('EV', 'Event'), ('AR', 'Arena'), ('DE', 'Death Match')], max_length=2),
        ),
    ]
