# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-27 10:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='armour',
        ),
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='shield',
        ),
        migrations.AddField(
            model_name='ability',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
