# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-28 08:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180427_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_line', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='hero',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Character'),
        ),
    ]
