# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-28 16:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180428_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
