# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-05 09:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180428_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
