# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180505_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nationality',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
