# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180526_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='english_translation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
