# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-29 16:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_line_english_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=10),
        ),
    ]
